packages:
  - .

minimumReleaseAge: 10080

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  better-sqlite3: true
  prisma: true
