/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSendEmailRouteImport } from './routes/api/sendEmail'
import { Route as ApiReadProjectsRouteImport } from './routes/api/readProjects'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminCreateProjectRouteImport } from './routes/api/admin/createProject'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/sendEmail',
  path: '/api/sendEmail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadProjectsRoute = ApiReadProjectsRouteImport.update({
  id: '/api/readProjects',
  path: '/api/readProjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCreateProjectRoute = ApiAdminCreateProjectRouteImport.update({
  id: '/api/admin/createProject',
  path: '/api/admin/createProject',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/panel': typeof PanelRoute
  '/projects': typeof ProjectsRoute
  '/signin': typeof SigninRoute
  '/api/readProjects': typeof ApiReadProjectsRoute
  '/api/sendEmail': typeof ApiSendEmailRoute
  '/api/admin/createProject': typeof ApiAdminCreateProjectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/panel': typeof PanelRoute
  '/projects': typeof ProjectsRoute
  '/signin': typeof SigninRoute
  '/api/readProjects': typeof ApiReadProjectsRoute
  '/api/sendEmail': typeof ApiSendEmailRoute
  '/api/admin/createProject': typeof ApiAdminCreateProjectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/panel': typeof PanelRoute
  '/projects': typeof ProjectsRoute
  '/signin': typeof SigninRoute
  '/api/readProjects': typeof ApiReadProjectsRoute
  '/api/sendEmail': typeof ApiSendEmailRoute
  '/api/admin/createProject': typeof ApiAdminCreateProjectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/panel'
    | '/projects'
    | '/signin'
    | '/api/readProjects'
    | '/api/sendEmail'
    | '/api/admin/createProject'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/panel'
    | '/projects'
    | '/signin'
    | '/api/readProjects'
    | '/api/sendEmail'
    | '/api/admin/createProject'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/panel'
    | '/projects'
    | '/signin'
    | '/api/readProjects'
    | '/api/sendEmail'
    | '/api/admin/createProject'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PanelRoute: typeof PanelRoute
  ProjectsRoute: typeof ProjectsRoute
  SigninRoute: typeof SigninRoute
  ApiReadProjectsRoute: typeof ApiReadProjectsRoute
  ApiSendEmailRoute: typeof ApiSendEmailRoute
  ApiAdminCreateProjectRoute: typeof ApiAdminCreateProjectRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sendEmail': {
      id: '/api/sendEmail'
      path: '/api/sendEmail'
      fullPath: '/api/sendEmail'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/readProjects': {
      id: '/api/readProjects'
      path: '/api/readProjects'
      fullPath: '/api/readProjects'
      preLoaderRoute: typeof ApiReadProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/createProject': {
      id: '/api/admin/createProject'
      path: '/api/admin/createProject'
      fullPath: '/api/admin/createProject'
      preLoaderRoute: typeof ApiAdminCreateProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PanelRoute: PanelRoute,
  ProjectsRoute: ProjectsRoute,
  SigninRoute: SigninRoute,
  ApiReadProjectsRoute: ApiReadProjectsRoute,
  ApiSendEmailRoute: ApiSendEmailRoute,
  ApiAdminCreateProjectRoute: ApiAdminCreateProjectRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
